language: ruby
rvm:
- 2.0.0
services:
- memcached
script:
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec
- bundle exec rspec